# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 865e8596790e63625055ea7910ca8c5bea3c0bce3edfcc16a8022cd7db0ce784e6965251522762ef557e1c51fc498f83569570d5f687ef5b16bc1781c1fe8221

test:
  secret_key_base: 38737ae994805a4b1553938c835e5ff7868cf9ca3dd3b7f74a22b0778c4ec3569a805e984a4a1ec796ce9768ed547907aa9733f2694245cf6745f3196a977c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
